### PR TITLE
Fix main window bugs

### LINKED ISSUE #98: Canceling TSV import throws unhandled exception
When a user has a table open and starts to select a file for TSV import, if the operation is canceled at the select file dialog an unhandled exception is thrown.

```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1762)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1645)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1364)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$324(ContextMenuContent.java:1317)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer$$Lambda$282/1084824391.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3724)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3452)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1728)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2461)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:348)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:273)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:382)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:553)
	at com.sun.glass.ui.View.notifyMouse(View.java:925)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$45(GtkApplication.java:126)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$43/584634336.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1759)
	... 43 more
Caused by: java.lang.NullPointerException
	at org.cirdles.topsoil.app.TopsoilMainWindow.importFromFile(TopsoilMainWindow.java:299)
	... 53 more
```

### PR DESCRIPTION
**Pull request by clementparizot**
May need a review/modifications

### CODE REVIEW

File: src/main/java/org/cirdles/topsoil/app/TopsoilMainWindow.java [hunk 1]
```diff
@@ -116,12 +116,18 @@ public void initialize(URL url, ResourceBundle resources) {
...
     Optional<TSVTable> getCurrentTable() {
         Optional<TSVTable> result = Optional.empty();
-        Tab currentTab = dataTableTabPane.getSelectionModel().getSelectedItem();
+        Tab currentTab = getCurrentTab();
+
+        if(currentTab==null)
+        {
+            createTab();
+            currentTab = getCurrentTab();
+        }
```
Comment (johnzeringue) [inline src/main/java/org/cirdles/topsoil/app/TopsoilMainWindow.java]: With some refactoring, the above is better written as:

``` java
Optional<Tab> currentTab = Optional.ofNullable(getCurrentTab()).orElse(createTab());
```

Of course, this might not belong here, but generally, `Optional` should be used whenever you itch to write `if (currentTab == null)`.

Comment (johnzeringue) [inline src/main/java/org/cirdles/topsoil/app/TopsoilMainWindow.java]: Also, please space as previous contributors have, i.e. `if<space>(currentTab<space>==<space>null)`.

**Comment by johnzeringue** [comment]
Again, please squash your commits. You'll also need to merge in my new changes to `js-charts` (sorry).

**Comment by johnzeringue** [comment]
Okay, sorry my comments have been a bit scattered. Here's the unified message.

This is my version of your `getCurrentTable()`:

``` java
Optional<TSVTable> getCurrentTable() {
    Tab currentTab = Optional.ofNullable(getCurrentTab()).orElse(createTab());
    Optional<TSVTable> result = Optional.of((TSVTable) currentTab.getContent()); 
    return result;
}
```

My problem with this is that result is no longer optional, so `Optional<TSVTable>` is not a good return type. Here's a revision with just `TSVTable` returned:

``` java
TSVTable getCurrentTable() {
    return (TSVTable) Optional.ofNullable(getCurrentTab()).orElse(createTab()).getContent();
}
```

This might read better in two or three lines, but you get the idea. However, now I don't like the fact that `getCurrentTable()` is creating a new tab when none exist. That really isn't implied by its name.

So maybe we need to be more clear about the purpose of methods and refactor around that. I think that `getCurrentTab()` should return the current tab if any exist and that `getCurrentTable()` should return the table in the current tab. Assuming then that `getCurrentTab()` returns `Optional<Tab>` and that `getCurrentTable()` returns `Optional<Table>`, we finally have the following for `getCurrentTable()`:

``` java
Optional<TSVTable> getCurrentTable() {
    return getCurrentTab().map(tab -> (TSVTable) tab.getContent());
}
```

To me, this reads much nicer and is more in line with what you'd expect from `getCurrentTable()` (non-destructivity).

@clementparizot, what are your thoughts?

**Comment by johnzeringue** [comment]
We need to figure out why this isn't building. If you rebase in the changes made in #105, it should make it easier to debug the Travis CI build.

File: src/test/java/org/cirdles/topsoil/app/TopsoilMainWindowTest.java [hunk 2]
```diff
@@ -31,5 +33,17 @@ public void start(Stage stage) throws Exception {
...
     }
-    
+
+//    @Test
+//    public void testCreateTab() {
+//        int size = ((TabPane) lookup("#dataTableTabPane").queryFirst()).getTabs().size();
+//        clickOn("Create Data Table");
+//        verifyThat("#dataTableTabPane",
+//                (TabPane tabPane) -> tabPane.getTabs().size() > 0);
+//    }
```
Comment (johnzeringue) [inline src/test/java/org/cirdles/topsoil/app/TopsoilMainWindowTest.java]: I'm fine with forgetting about trying to test this with as much time as we've sunk into it, but let's just get rid of it altogether (no comments).
